#!/bin/bash
set -e

#TODO: compile strace with lib-unwind for stack traces at each system call

strace_tmpfile=$(mktemp /tmp/huh.strace.XXXXXX)
echo $strace_tmpfile
#echo $db_tmpfile
strace -x -y -yy -v -T -ttt -q -f -i -o $strace_tmpfile "$@"
lein run $strace_tmpfile


